bundler_args: "--without assets:development:production"
rvm:
  - 2.2.3
  - 1.29.1
  - rbx
  - rbx-2.0
  - ree
env: "RAILS_ENV=test"

language: ruby

script:
  - bundle exec ruby -Itest test/functional/drains_controller_test.rb -n 'test_should_get_index'

cache: bundler

# whitelist
branches:
  only:
    - master
    - development

