bundler_args: "--without assets:development:production"
rvm:
  - 2.2.3
env: "RAILS_ENV=test"

language: ruby

before_script:
  - psql -c 'create database twaamtaro_test;' -U postgres
  - psql -c 'create table mitaro_dar (gid integer PRIMARY KEY, the_geom varchar(254));' -U postgres
  - "cp ./.travis.database.yml ./config/database.yml"

script:
  - bundle exec rake db:migrate
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec ruby -Itest test/functional/drains_controller_test.rb -n 'test_should_get_index'

cache: bundler

# whitelist
branches:
  only:
    - master
    - development

